const allSymbols = ["t1", "t2", "t3", "t4", "t5", "t6", "t7","t8","t9","t10","t11","t12"];

export const testingRounds = [
    {
        _id: "0",
        taskName: "Task 1",
        symbols: ["t1", "t3", "t5"],
        answer: "t1",
    }
]

export const taskRounds =[
    {
        _id: "0",
        taskName: "Task 1",
        symbols: allSymbols,
        answer: "t1",
      },
      {
        _id: "1",
        taskName: "Task 2",
        symbols: allSymbols,
        answer: "t2",
      },
      {
        _id: "2",
        taskName: "Task 3",
        symbols: allSymbols,
        answer: "t3",
      },
      {
        _id: "3",
        taskName: "Task 4",
        symbols: allSymbols,
        answer: "t4",
      },
      {
        _id: "4",
        taskName: "Task 5",
        symbols: allSymbols,
        answer: "t5",
      },
      {
        _id: "5",
        taskName: "Task 6",
        symbols: allSymbols,
        answer: "t6",
      },
      {
        _id: "6",
        taskName: "Task 7",
        symbols: allSymbols,
        answer: "t7",
      },
      {
        _id: "7",
        taskName: "Task 8",
        symbols: allSymbols,
        answer: "t8",
      },
      {
        _id: "8",
        taskName: "Task 9",
        symbols: allSymbols,
        answer: "t9",
      },
      {
        _id: "9",
        taskName: "Task 10",
        symbols: allSymbols,
        answer: "t10",
      },
      {
        _id: "10",
        taskName: "Task 11",
        symbols: allSymbols,
        answer: "t11",
      },
      {
        _id: "11",
        taskName: "Task 12",
        symbols: allSymbols,
        answer: "t12",
      },
      {
        _id: "12",
        taskName: "Task 13",
        symbols: allSymbols,
        answer: "t1",
      },
      {
        _id: "13",
        taskName: "Task 14",
        symbols: allSymbols,
        answer: "t2",
      },
      {
        _id: "14",
        taskName: "Task 15",
        symbols: allSymbols,
        answer: "t3",
      },
]

export const NToLabels = 
{6: 
{410: ['crab','down','frog','obgyn','rabbit','sad','sofa','squat'],
411: ['angel', 'crab', 'fish', 'frog', 'rabbit'],
412: ['bench', 'bunny', 'crab', 'tall', 'zen'],
413: ['couch', 'kiss', 'tall', 'v', 'vee'],
414: ['bunny', 'couch', 'hole', 'lift', 'zen'],
415: ['bunny', 'couch', 'crab', 'sunris', 'whale'],
416: ['bench', 'bunny', 'cheer', 'crab', 'kiss'],
417: ['bone', 'bunny', 'crab', 'lowsun', 'upsun'],
418: ['crab', 'lifter', 'splash', 'sumo', 'whale'],
419: ['bunny', 'crab', 'frog', 'hug', 'kiss'],
420: ['bell', 'bunny', 'crab', 'kiss', 'squat'],
421: ['ball', 'book', 'couch', 'crab', 'keyhol'],
422: ['a', 'couch', 'crab', 'tall', 'topdot', 'twins'],
434: ['crab', 'float', 'frog', 'read', 'readin'],
435: ['ball', 'frog', 'sit', 'totem', 'whale'],
436: ['crab', 'keyhol', 'read', 'whale', 'x'],
437: ['champ', 'couch', 'crab', 'hug', 'rabbit', 'yoga'],
438: ['crab', 'down', 'frog', 'lotus', 'sofa']},
8: 
{392: ['bell', 'boat', 'crab', 'frog', 'hockey'],
393: ['couch', 'frog', 'rabbit', 'whale', 'x'],
394: ['a', 'crab', 'flat', 'frog', 'tall', 'yoga'],
395: ['ballup', 'bed', 'crab', 'topdot', 'yoga'],
396: ['book', 'couch', 'crab', 'fish', 'frog', 'whale'],
397: ['flat', 'frog', 'squat', 'taller', 'whale'],
398: ['bunny', 'cheer', 'crab', 'frog', 'hiball', 'rabbit'],
399: ['a', 'bench', 'crab', 'down', 'hooray', 'whale'],
425: ['crab', 'frog', 'sword', 'x', 'xball'],
426: ['ballup', 'bowtie', 'crab', 'frog', 'kissin'],
427: ['book', 'couch', 'crab', 'fish', 'keyhol', 'yoga'],
428: ['crab', 'frog', 'hiball', 'rabbit', 'whale'],
429: ['bunny', 'couch', 'crab', 'frog', 'tall'],
430: ['ball', 'book', 'crab', 'frog', 'widest'],
431: ['backs', 'circle', 'crab', 'frog', 'vase'],
432: ['ball', 'couch', 'crab', 'kiss', 'yoga'],
433: ['crab', 'flat', 'frog', 'rabbit', 'tall']},
24: 
{222: ['bunny', 'couch', 'crab', 'frog', 'kiss'],
223: ['couch', 'crab', 'squat', 'whale', 'winner'],
224: ['bunny', 'couch', 'crab', 'tall', 'x'],
225: ['bunny', 'couch', 'crab', 'frog', 'yoga'],
226: ['bell', 'bowtie', 'couch', 'crab', 'rabbit'],
227: ['bunny', 'crab', 'frog', 'keyhol', 'yoga'],
229: ['bunny', 'crab', 'frog', 'rabbit', 'tall'],
230: ['crab', 'frog', 'kiss', 'rabbit', 'yoga'],
231: ['bunny', 'couch', 'crab', 'hiball', 'loball'],
708: ['bowtie', 'crab', 'frog', 'tall', 'whale'],
716: ['bunny', 'crab', 'frog', 'whale', 'yoga'],
717: ['bunny', 'couch', 'crab', 'frog', 'kiss'],
718: ['book', 'crab', 'flat', 'frog', 'rabbit'],
727: ['ball', 'bunny', 'crab', 'frog', 'keyhol'],
728: ['ball', 'bunny', 'crab', 'frog', 'yoga']},
50: 
{292: ['book', 'bunny', 'crab', 'frog'],
293: ['bunny', 'couch', 'crab', 'frog', 'kiss'],
294: ['bunny', 'crab', 'frog'],
295: ['ball', 'bunny', 'crab', 'frog', 'tall'],
296: ['couch', 'crab', 'frog', 'tall', 'yoga'],
349: ['ball', 'bunny', 'crab', 'frog', 'kiss'],
350: ['bunny', 'couch', 'crab', 'frog', 'tall'],
351: ['bunny', 'crab', 'frog', 'kiss', 'tall'],
352: ['bunny', 'crab', 'frog', 'yoga'],
353: ['bunny', 'couch', 'crab', 'frog'],
366: ['bunny', 'crab', 'tall', 'yoga'],
370: ['couch', 'crab', 'frog', 'tall'],
371: ['bunny', 'couch', 'crab', 'frog', 'hiball'],
372: ['ball', 'bunny', 'couch', 'crab', 'frog'],
383: ['bunny', 'crab', 'hiball', 'kiss']},
2: 
{234: ['adot','bowtie','crab','hooray','hug','vagina','xdot'],
237: ['buddha', 'fly', 'frog', 'hug', 'sad'],
238: ['bunny','crab','hiball','loball','narrow','sittin','stop','vase'],
239: ['crab', 'lowbal', 'thin', 'wide', 'x'],
240: ['bowtie', 'couch', 'crab', 'kiss', 'yoga'],
241: ['couch', 'crab', 'hole', 'kiss', 'moon', 'widest', 'x'],
242: ['cheer', 'downba', 'plate', 'upball', 'vase'],
243: ['catch', 'couple', 'crab', 'hotdog', 'rabbit'],
244: ['armsup', 'bfly', 'crab', 'rabbit', 'twohed', 'yoga'],
245: ['book', 'closed', 'rabbit', 'wide', 'x'],
247: ['bunny','crab','cutter','ghost','reader','sitter','skydiv','yoga'],
248: ['a', 'crab', 'keyhol', 'sunset', 'woman'],
249: ['car', 'crab', 'kiss', 'pray', 'yoga'],
250: ['beetle', 'crab', 'moth', 'whale', 'yoga'],
251: ['abunny', 'jump', 'ov', 'shrug', 'squat', 'tall', 'xo'],
253: ['amen', 'bookup', 'couch', 'kissin', 'third'],
260: ['dot', 'flydot', 'frog', 'hidot', 'keyhol'],
261: ['couch', 'dino', 'shamoo', 'stop', 'vball'],
262: ['boo', 'bunny', 'lotus', 'menace', 'whale'],
263: ['bunny', 'couch', 'frog', 'jacks', 'vase'],
264: ['balbtw','banana','dotlow','kisses','kissin','xdotup','yay'],
265: ['crab', 'fly', 'frog', 'kiss', 'wings'],
266: ['ball','clown','crab','goal','heart','rabbit','whale'],
267: ['dotdwn', 'flat', 'narrow', 'v', 'x'],
268: ['armup', 'balbot', 'baltop', 'bowbal', 'crab', 'thin'],
269: ['crab', 'flat', 'scisor', 'talcra', 'turtle', 'yoga'],
272: ['boxer', 'crab', 'flat', 'flatst', 'hole', 'tall'],
273: ['hockey', 'hug', 'sit', 'sittin', 'sofa'],
274: ['ball', 'clubs', 'crab', 'tall', 'topbal'],
275: ['closed', 'crab', 'frog', 'ghost', 'hiball'],
276: ['couch', 'hug', 'kiss', 'kneel', 'squat'],
277: ['crossx', 'earsup', 'kissin', 'readin', 'sofa'],
278: ['crab', 'flat', 'tallcr', 'thin', 'yoga'],
280: ['ball', 'bunny', 'crab', 'tall', 'triang', 'wings'],
281: ['book', 'crab', 'flex', 'squat', 'vagina'],
283: ['crab', 'frog', 'hug', 'kiss', 'smile'],
284: ['frog', 'horse', 'jumpin', 'readin', 'squat'],
285: ['bunny', 'couch', 'down', 'frog', 'kiss', 'knot'],
286: ['ball', 'ballup', 'gloves', 'moth', 'person'],
287: ['bunny', 'frog', 'hiball', 'smile', 'sunset', 'teletu'],
297: ['armsup', 'backs', 'book', 'crab', 'kiss', 'xman'],
298: ['arms', 'ball', 'bowtie', 'frog', 'hole'],
299: ['alien', 'armsup', 'boy', 'crab', 'hug', 'sunset'],
300: ['crab', 'hug', 'medi', 'onhead', 'stop'],
301: ['bowtie', 'handup', 'keyhol', 'kiss', 'tiedup'],
302: ['crab', 'hugs', 'rabbit', 'sittin', 'two'],
303: ['frog', 'moth', 'tongs', 'woman', 'yoga'],
304: ['bunny', 'crab', 'hug', 'splash', 'sumo'],
305: ['crab', 'eye', 'hotdog', 'lock', 'sit'],
317: ['tllest', 'whale', 'wide', 'wings', 'yoga'],
319: ['butt', 'crab', 'frog', 'narrow', 'yoga'],
321: ['crab', 'dance', 'hugs', 'sit', 'sofa'],
322: ['book', 'crab', 'flower', 'frog', 'keyhol'],
331: ['blob', 'couple', 'crab', 'rabbit', 'smile'],
332: ['cheer', 'crab', 'flat', 'loball', 'tall'],
333: ['clubs', 'couple', 'fly', 'golf', 'man', 'x'],
335: ['book', 'bunny', 'crab', 'keyhol', 'muscle'],
337: ['dogs', 'frog', 'rabbit', 'seals', 'whale'],
338: ['couple', 'crab', 'faces', 'hulk', 'yoga'],
339: ['baby', 'couch', 'crab', 'head', 'vase'],
341: ['floaty', 'hiarms', 'hiball', 'hole', 'loball'],
343: ['crab', 'frog', 'hiball', 'kiss', 'pray'],
345: ['crab', 'fightr', 'frog', 'ship', 'sofa'],
357: ['book', 'crab', 'fly', 'rabbit', 'sumo', 'teepee', 'vase'],
359: ['boxing', 'crab', 'rabbit', 'whale', 'wings'],
360: ['book', 'crab', 'hug', 'kiss', 'x'],
363: ['bed', 'love', 'ohmmm', 'power', 'read', 'shark'],
374: ['a', 'butts', 'couch', 'frog', 'sit'],
380: ['book', 'crab', 'cross', 'rabbit', 'vagina', 'yeller'],
400: ['down', 'frog', 'space', 'tall', 'wide', 'x'],
401: ['anthea', 'couch', 'crab', 'hover', 'lotus'],
402: ['bird', 'bunny', 'crab', 'frog', 'vase'],
403: ['bell', 'bone', 'btrfly', 'kissin', 'spread'],
405: ['ball', 'crab', 'rabbit', 'statue', 'sword', 'table'],
406: ['book', 'happy', 'kiss', 'sad', 'yoga'],
407: ['blowup', 'boxer', 'crab', 'kick', 'kickb'],
409: ['bird', 'crab', 'win', 'woman', 'yay']}}